services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-php
    ports:
      - "8080:80"
    volumes:
      - ./API-PHP:/var/www/html
      - sqlite-data:/var/www/html/data

volumes:
  sqlite-data:
